[package]
name = "kicad_halftone"
version = "0.1.0"
authors = ["Ian Rees <ian.rees@gmail.com>"]

[features]
# Still trying to get this part figured out...
gui = ["iui"]

[dependencies]
image = "0.19.0"
iui = {version = "0.3", optional=true}