[package]
name = "kicad_halftone"
version = "0.1.0"
authors = ["Ian Rees <ian.rees@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.5", features = ["cargo", "derive"] }
image = "0.24"
