[package]
name = "kicad_halftone"
version = "0.2.0"
authors = ["Ian Rees <code@ianrees.nz>"]
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["cargo", "derive"] }
image = "0.24"
